### PR TITLE
Update and repair

### PR DESCRIPTION
**Pull request by xpyxel**
This is a update that should hopefully fix a lot of issues and update everything. This could or could not be broken after this, however  from what I can tell from testing on my own system it works as intended.

- [x] Update `mlua` and `clap` to their latest versions
- [x] Add the `vendored` feature to `mlua` to remove system dependecy
- [x] Remove `help.clml` as the file is no longer being used
- [x] Repair errors with how clap is used due to updating
- [x] Allow `non-fmt-panic` warning as it's not causing actual errors
- [x] Removes the custom build script as it's no longer required

### CODE REVIEW

**Comment by K4rakara** [comment]
Whats broken about the build script? Its required for generating the ASCII art

**Comment by xpyxel** [comment]
> Whats broken about the build script? Its required for generating the ASCII art
> 
> EDIT:
> 
> Note that if you've built the project in the past, the ASCII art will still be there, and you wont get build errors. Anyone who would build this branch from scratch would get a build error.

ah i see, the build script required the `help.clml` file, im assuming that's used to generate the ASCII art?

**Comment by K4rakara** [comment]
> ah i see, the build script required the `help.clml` file, im assuming that's used to generate the ASCII art?

Help.clml makes the output of `freshfetch --help`, the ascii art is generated by the files in `src/assets/ascii_art/`

**Comment by xpyxel** [comment]
> > ah i see, the build script required the `help.clml` file, im assuming that's used to generate the ASCII art?
> 
> Help.clml makes the output of `freshfetch --help`, the ascii art is generated by the files in `src/assets/ascii_art/`

Alright i'll look into fixing it, give me a moment.

**Comment by xpyxel** [comment]
Should be fixed and working now, `help.clml` and `build.rs` is back and working correctly.

**Pull request merged**
